tendencia_choices = [
    ('Sin Información', 'Sin Información'),
    ('Izquierda', 'Izquierda'),
    ('Derecha', 'Derecha'),
    ('Centro-Izquierda', 'Centro-Izquierda'),
    ('Centro-Derecha', 'Centro-Derecha'),
    ('Centro', 'Centro'),
]

convocatoria_choices = [
    ('Alto','Alto'),
    ('Medio','Medio'),
    ('Bajo','Bajo'),
]

estatus_ficha_choices = [
    ('Revisado','Revisado'),
    ('Corregir','Corregir'),
    ('En proceso', 'En proceso')
]

riesgo_choices = [
    ('Bajo','Bajo'),
    ('Medio','Medio'),
    ('Alto','Alto'),
]
    
sexo_choices = [
    ('Femenino', 'Femenino'),
    ('Masculino', 'Masculino'),
    ('No definido', 'No definido'),
]

estado_civil_choices = [
    ('Soltero', 'Soltero'),
    ('Soltera', 'Soltera'),
    ('Casada', 'Casada'),
    ('Casado', 'Casado'),
    ('Divorciada', 'Divorciada'),
    ('Divorciado', 'Divorciado'),
    ('Union Libre', 'Union Libre'),
    ('Otro', 'Otro'),
]

tipo_org = [
    ('Colectivo Feminista', 'Colectivo Feminista'), 
    ('Colectivo Ciclista', 'Colectivo Ciclista'),
    ('Colectivo Civil', 'Colectivo Civil'), 
    ('Organización Sindical', 'Organización Sindical'),
    ('Organización Social', 'Organización Social'), 
    ('Organización Política', 'Organización Política'),
    ('Organización Estudiantil', 'Organización Estudiantil'),
    ('Colectivo LGBTTTIQ+', 'Colectivo LGBTTTIQ+')
]

tipo_contendiente_choices = [
    ('Presidenta Municipal', 'Presidenta Municipal'),
    ('Presidente Municipal', 'Presidente Municipal'),
    ('Diputada Federal', 'Diputada Federal'),
    ('Diputado Federal', 'Diputado Federal'),
    ('Diputada Local', 'Diputada Local'),
    ('Diputado Local', 'Diputado Local'),
    ('Regidora', 'Regidora'),
    ('Regidor', 'Regidor'),
    ('Candidato a Presidencia Municipal', 'Candidato a Presidencia Municipal'),
    ('Candidata a Presidencia Municipal', 'Candidata a Presidencia Municipal'),
    ('Candidata a Diputación Federal', 'Candidata a Diputación Federal'),
    ('Candidato a Diputación Federal', 'Candidato a Diputación Federal'),
    ('Candidata a Diputación Local', 'Candidata a Diputación Local'),
    ('Candidato a Diputación Local', 'Candidato a Diputación Local'),
    ('Militante', 'Militante'),
    ('Otro', 'Otro'),
]

periodo_electoral_choices = [
    ('2022 - 2024', '2022 - 2024'),
    ('2025 - 2027', '2025 - 2027'),
]

protesta_choices = [
    ('Si','Si'),
    ('No','No'),
]

partido_siglas_choices = [
    ('PAN', 'PAN'),
    ('PRI', 'PRI'),
    ('PRD', 'PRD'),
    ('PT', 'PT'),
    ('PVEM', 'PVEM'),
    ('MC', 'MC'),
    ('MORENA', 'MORENA'),
    ('PES', 'PES'),
    ('RSP', 'RSP'),
    ('FM', 'FM'),
    ('JUNTOS HAREMOS HISTORIA FEDERAL', 'JUNTOS HAREMOS HISTORIA FEDERAL'),
    ('VA POR EL ESTADO DE MÉXICO', 'VA POR EL ESTADO DE MÉXICO'),
    ('VA POR ATLAUTLA', 'VA POR ATLAUTLA'),
    ('JUNTOS HAREMOS HISTORIA LOCAL', 'JUNTOS HAREMOS HISTORIA LOCAL'),
    ('JUNTOS HAREMOS HISTORIA EN EL ESTADO DE MÉXICO', 'JUNTOS HAREMOS HISTORIA EN EL ESTADO DE MÉXICO'),
    ('CANDIDATO INDEPENDIENTE', 'CANDIDATO INDEPENDIENTE'),
    ('NAEM', 'NAEM'),
]

estado_choices = [
    ('Aguascalientes', 'Aguascalientes'),
    ('Baja California', 'Baja California'),
    ('Baja California Sur', 'Baja California Sur'),
    ('Campeche', 'Campeche'),
    ('Chiapas', 'Chiapas'),
    ('Chihuahua', 'Chihuahua'),
    ('Ciudad de México', 'Ciudad de México'),
    ('Coahuila', 'Coahuila'),
    ('Colima', 'Colima'),
    ('Durango', 'Durango'),
    ('Estado de México ', 'Estado de México '),
    ('Guanajuato', 'Guanajuato'),
    ('Guerrero', 'Guerrero'),
    ('Hidalgo', 'Hidalgo'),
    ('Jalisco', 'Jalisco'),
    ('Michoacán', 'Michoacán'),
    ('Morelos', 'Morelos'),
    ('Nayarit', 'Nayarit'),
    ('Nuevo León', 'Nuevo León'),
    ('Oaxaca', 'Oaxaca'),
    ('Puebla', 'Puebla'),
    ('Querétaro', 'Querétaro'),
    ('Quintana Roo', 'Quintana Roo'),
    ('San Luis Potosí', 'San Luis Potosí'),
    ('Sinaloa', 'Sinaloa'),
    ('Sonora', 'Sonora'),
    ('Tabasco', 'Tabasco'),
    ('Tamaulipas', 'Tamaulipas'),
    ('Tlaxcala', 'Tlaxcala'),
    ('Veracruz', 'Veracruz'),
    ('Yucatán', 'Yucatán'),
    ('Zacatecas', 'Zacatecas'),
]

abreviatura_choices = [
    ('Andador', 'Andador'),
    ('Avenida', 'Avenida'),
    ('Boulevar', 'Boulevar'),
    ('Calle', 'Calle'),
    ('Calzada', 'Calzada'),
    ('Carretera', 'Carretera'),
    ('Cerrada', 'Cerrada'),
    ('Circuito', 'Circuito'),
    ('Corredor', 'Corredor'),
    ('Prolongación', 'Prolongación'),
    ('Vía', 'Vía'),
]

marca_choices = [
    ('Abarth', 'Abarth'),
    ('Alfa Romeo', 'Alfa Romeo'),
    ('Aro', 'Aro'),
    ('Asia', 'Asia'),
    ('Asia Motors', 'Asia Motors'),
    ('Aston Martin', 'Aston Martin'),
    ('Audi', 'Audi'),
    ('Austin', 'Austin'),
    ('Auverland', 'Auverland'),
    ('Bentley', 'Bentley'),
    ('Bertone', 'Bertone'),
    ('Bmw', 'Bmw'),
    ('Cadillac', 'Cadillac'),
    ('Chevrolet', 'Chevrolet'),
    ('Chrysler', 'Chrysler'),
    ('Citroen', 'Citroen'),
    ('Corvette', 'Corvette'),
    ('Dacia', 'Dacia'),
    ('Daewoo', 'Daewoo'),
    ('Daf', 'Daf'),
    ('Daihatsu', 'Daihatsu'),
    ('Daimler', 'Daimler'),
    ('Dodge', 'Dodge'),
    ('Ferrari', 'Ferrari'),
    ('Fiat', 'Fiat'),
    ('Ford', 'Ford'),
    ('Galloper', 'Galloper'),
    ('Gmc', 'Gmc'),
    ('Honda', 'Honda'),
    ('Hummer', 'Hummer'),
    ('Hyundai', 'Hyundai'),
    ('Infiniti', 'Infiniti'),
    ('Innocenti', 'Innocenti'),
    ('Isuzu', 'Isuzu'),
    ('Iveco', 'Iveco'),
    ('Iveco-pegaso', 'Iveco-pegaso'),
    ('Jaguar', 'Jaguar'),
    ('Jeep', 'Jeep'),
    ('Kia', 'Kia'),
    ('Lada', 'Lada'),
    ('Lamborghini', 'Lamborghini'),
    ('Lancia', 'Lancia'),
    ('Land-rover', 'Land-rover'),
    ('Ldv', 'Ldv'),
    ('Lexus', 'Lexus'),
    ('Lotus', 'Lotus'),
    ('Mahindra', 'Mahindra'),
    ('Maserati', 'Maserati'),
    ('Maybach', 'Maybach'),
    ('Mazda', 'Mazda'),
    ('Mercedes-benz', 'Mercedes-benz'),
    ('Mg', 'Mg'),
    ('Mini', 'Mini'),
    ('Mitsubishi', 'Mitsubishi'),
    ('Morgan', 'Morgan'),
    ('Nissan', 'Nissan'),
    ('Opel', 'Opel'),
    ('Peugeot', 'Peugeot'),
    ('Pontiac', 'Pontiac'),
    ('Porsche', 'Porsche'),
    ('Renault', 'Renault'),
    ('Rolls-royce', 'Rolls-royce'),
    ('Rover', 'Rover'),
    ('Saab', 'Saab'),
    ('Santana', 'Santana'),
    ('Seat', 'Seat'),
    ('Skoda', 'Skoda'),
    ('Smart', 'Smart'),
    ('Ssangyong', 'Ssangyong'),
    ('Subaru', 'Subaru'),
    ('Suzuki', 'Suzuki'),
    ('Talbot', 'Talbot'),
    ('Tata', 'Tata'),
    ('Toyota', 'Toyota'),
    ('Umm', 'Umm'),
    ('Vaz', 'Vaz'),
    ('Volkswagen', 'Volkswagen'),
    ('Volvo', 'Volvo'),
    ('Wartburg', 'Wartburg'),
]