# Generated by Django 3.2.8 on 2021-10-14 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(blank=True, max_length=18, unique=True, verbose_name='CURP')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apaterno', models.CharField(max_length=25, verbose_name='Apellido Paterno')),
                ('amaterno', models.CharField(max_length=25, verbose_name='Apellido Materno')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='persona/fotos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fechas de Nacimiento')),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de Nacimiento')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('edo_civil', models.CharField(choices=[('S', 'Soltero(a)'), ('M', 'Casado(a)'), ('U', 'Unión libre'), ('D', 'Divorciado(a) y/o Separado(a)')], default='S', max_length=1)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio')),
                ('calle', models.TextField(blank=True, max_length=40, null=True, verbose_name='Calle')),
                ('no', models.CharField(blank=True, max_length=5, verbose_name='Número')),
                ('no_int', models.CharField(blank=True, max_length=5, verbose_name='Número Int.')),
                ('lic_conducir', models.CharField(blank=True, max_length=25, verbose_name='Licencia de conducir')),
                ('tel_casa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de casa')),
                ('tel_cel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono celular')),
                ('nacionalidad', models.CharField(choices=[('M', 'Mexicano'), ('E', 'Extranjero')], default='M', max_length=1)),
                ('correo', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo')),
                ('escolaridad', models.CharField(blank=True, max_length=255, verbose_name='Escolaridad')),
                ('f_registo', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('f_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.estado')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_curso', models.DateField(blank=True, null=True)),
                ('duracion', models.DateField(blank=True, null=True)),
                ('documento', models.DateField(blank=True, null=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.municipio')),
            ],
        ),
    ]
