# Generated by Django 3.2.8 on 2021-10-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='f_modificado',
            field=models.DateTimeField(verbose_name='Fecha de modificación'),
        ),
    ]
