# Generated by Django 3.2.8 on 2021-10-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_persona_f_modificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='f_modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
    ]
