# Generated by Django 3.0.4 on 2021-10-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_curso_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nacionalidad',
        ),
        migrations.AlterField(
            model_name='persona',
            name='edo_civil',
            field=models.CharField(choices=[('S', 'Soltero(a)'), ('M', 'Casado(a)'), ('U', 'Unión libre'), ('D', 'Divorciado(a) y/o Separado(a)')], default='S', max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo'),
        ),
    ]
