# Generated by Django 3.2.8 on 2021-10-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_persona_f_modificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='f_modificado',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='f_registo',
        ),
    ]
