# Generated by Django 3.2.8 on 2021-10-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20211019_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='foto',
        ),
    ]
